version: "3.9"

services:
  app:
    build:
      context: .
      args:
        - DEV=true
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    command:
      sh -c "poetry run uvicorn main:app --host 0.0.0.0 --reload"

