---
name: Checks

on: [push]

jobs:
  test-lint:
    name: Test and Linter
    runs-on: ubuntu-20.04
    steps:
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build Image
        run: docker-compose build
      - name: Test
        run: docker-compose run --rm app sh -c "poetry run pytest"
      - name: Lint
        run: docker-compose run --rm app sh -c "poetry run flake8"

